// ASIC Block 1 testbench.
//
// Do NOT edit this file. Run it with `make`, and it runs nine tests (fifteen checks
// in total) against your design. When every check says PASS, your design is done.
//
// (In Block 2 you write a testbench yourself. For now, read this one if you're
//  curious. It isn't complicated: it's mostly waiting and counting.)

`default_nettype none
`timescale 1ns / 1ns

module tb_traffic_light;

    // ================ what the spec says the timing should be ================
    localparam GREEN_TIME  = 12;
    localparam YELLOW_TIME = 4;
    localparam RED_TIME    = 10;
    localparam MIN_GREEN   = 4;

    // ================ wires to the design under test ================
    reg        clk   = 0;
    reg        rst_n = 0;
    reg  [7:0] ui_in = 8'h00;
    wire [7:0] uo_out, uio_out, uio_oe;

    always #5 clk = ~clk;          // one clock tick every 10 ns

    tt_um_traffic_light dut (
        .ui_in   (ui_in),
        .uo_out  (uo_out),
        .uio_in  (8'h00),
        .uio_out (uio_out),
        .uio_oe  (uio_oe),
        .ena     (1'b1),
        .clk     (clk),
        .rst_n   (rst_n)
    );

    wire car_red    = uo_out[0];
    wire car_yellow = uo_out[1];
    wire car_green  = uo_out[2];
    wire walk       = uo_out[3];

    // ================ scoreboard ================
    integer passed = 0;
    integer failed = 0;

    task check(input condition, input [1023:0] name);
        begin
            if (condition) begin
                $display("  [PASS]  %0s", name);
                passed = passed + 1;
            end else begin
                $display("  [FAIL]  %0s", name);
                failed = failed + 1;
            end
        end
    endtask

    // ================ measure how long each color stays on ================
    // Every time the lights change, record how many ticks the previous color lasted.
    reg  [2:0] prev_lights = 3'bxxx;
    integer    cur_dur     = 0;
    integer    last_green  = -1;
    integer    last_yellow = -1;
    integer    last_red    = -1;

    always @(posedge clk) begin
        if (rst_n) begin
            if (uo_out[2:0] === prev_lights) begin
                cur_dur = cur_dur + 1;
            end else begin
                case (prev_lights)
                    3'b100: last_green  = cur_dur;   // uo_out[2] is green
                    3'b010: last_yellow = cur_dur;   // uo_out[1] is yellow
                    3'b001: last_red    = cur_dur;   // uo_out[0] is red
                    default: ;
                endcase
                cur_dur     = 1;
                prev_lights = uo_out[2:0];
            end
        end
    end

    // ================ one-hot monitor, runs the whole time ================
    integer onehot_errors = 0;
    always @(posedge clk) begin
        if (rst_n && ((car_red + car_yellow + car_green) !== 1)) begin
            if (onehot_errors < 3)
                $display("     ...at tick %0t: %0d lights on at once (should be exactly 1)",
                         $time / 10, car_red + car_yellow + car_green);
            onehot_errors = onehot_errors + 1;
        end
    end

    // ================ walk monitor, runs the whole time ================
    // walk must be on for all of RED and off the rest of the time.
    integer walk_errors = 0;
    always @(posedge clk) begin
        if (rst_n && (walk !== car_red)) begin
            if (walk_errors < 3)
                $display("     ...at tick %0t: walk is %b while red is %b (walk should match red)",
                         $time / 10, walk, car_red);
            walk_errors = walk_errors + 1;
        end
    end

    // ================ helper: press the button for exactly one tick ================
    task press_button;
        begin
            @(negedge clk);
            ui_in[0] = 1'b1;
            @(negedge clk);
            ui_in[0] = 1'b0;
        end
    endtask

    // Wait until the light has just turned green.
    task wait_for_green_start;
        begin
            @(posedge clk);
            while (car_green !== 1'b0) @(posedge clk);   // make sure green is off first
            while (car_green !== 1'b1) @(posedge clk);   // then wait for it to come on
        end
    endtask

    // ================ watchdog, so a broken design stops instead of hanging ================
    initial begin
        #12000;
        $display("");
        $display("  TIMEOUT: the light never reached a state the test was waiting for.");
        $display("  If you just copied the starter file, that is expected. Fill in the TODOs.");
        $display("  Otherwise, the last TEST line above is the one that got stuck. Open the");
        $display("  waveform (make wave). If state or timer shows x, your reset doesn't set it.");
        $display("");
        $display("  %0d passed, %0d failed", passed, failed);
        $finish;
    end

    // ================ the tests ================
    initial begin
        $dumpfile("traffic.vcd");
        $dumpvars(0, tb_traffic_light);

        $display("");
        $display("=====================================================");
        $display("  ASIC Block 1: Traffic Light Controller");
        $display("=====================================================");
        $display("");

        // ==== reset ====
        repeat (3) @(negedge clk);
        rst_n = 1'b1;
        @(posedge clk);
        #1;

        $display("TEST 1: after reset");
        check(car_red === 1'b1, "light is RED after reset");
        check(walk    === 1'b1, "walk signal is on during RED");
        $display("");

        // ==== one clean cycle, nobody presses the button ====
        $display("TEST 2: one full cycle with no button press");
        wait_for_green_start;
        repeat (GREEN_TIME + YELLOW_TIME + RED_TIME + 2) @(posedge clk);
        $display("     measured: green=%0d  yellow=%0d  red=%0d ticks",
                 last_green, last_yellow, last_red);
        check(last_green  == GREEN_TIME,  "green lasts 12 ticks");
        check(last_yellow == YELLOW_TIME, "yellow lasts 4 ticks");
        check(last_red    == RED_TIME,    "red lasts 10 ticks");
        $display("");

        // ==== button pressed in the middle of green ====
        $display("TEST 3: button pressed partway through green");
        wait_for_green_start;
        repeat (5) @(posedge clk);
        press_button;
        while (car_green === 1'b1) @(posedge clk);
        @(posedge clk); #1;
        $display("     measured: green lasted %0d ticks (should be less than 12)", last_green);
        check(last_green < GREEN_TIME, "a mid-green press cuts green short");
        $display("");

        // ==== button pressed the instant green starts ====
        $display("TEST 4: button pressed the instant green starts");
        wait_for_green_start;
        press_button;
        while (car_green === 1'b1) @(posedge clk);
        @(posedge clk); #1;
        $display("     measured: green lasted %0d ticks (should be exactly %0d)",
                 last_green, MIN_GREEN);
        check(last_green >= MIN_GREEN, "cars always get at least 4 ticks of green");
        check(last_green == MIN_GREEN,
              "an early press is REMEMBERED and acted on once min-green is met");
        $display("");

        // ==== button pressed during red ====
        $display("TEST 5: button pressed during red");
        while (car_red !== 1'b1) @(posedge clk);
        press_button;
        wait_for_green_start;
        repeat (GREEN_TIME + 2) @(posedge clk);
        $display("     measured: the next green lasted %0d ticks (should be a full 12)", last_green);
        check(last_green == GREEN_TIME, "a press during red does not shorten the next green");
        $display("");

        // ==== button pressed during yellow ====
        $display("TEST 6: button pressed during yellow");
        while (car_yellow !== 1'b1) @(posedge clk);
        press_button;
        wait_for_green_start;
        repeat (GREEN_TIME + 2) @(posedge clk);
        $display("     measured: the next green lasted %0d ticks (should be a full 12)", last_green);
        check(last_green == GREEN_TIME, "a press during yellow does not shorten the next green");
        $display("");

        // ==== button pressed on the very last tick of red ====
        $display("TEST 7: button pressed on the last tick of red");
        while (car_red !== 1'b1) @(posedge clk);
        repeat (RED_TIME - 2) @(posedge clk);   // the pulse lands on red's final tick
        press_button;
        while (car_green !== 1'b1) @(posedge clk);
        while (car_green === 1'b1) @(posedge clk);
        @(posedge clk); #1;
        $display("     measured: the next green lasted %0d ticks (should be a full 12)", last_green);
        check(last_green == GREEN_TIME, "a press on the last tick of red does not carry into green");
        $display("");

        // ==== reset in the middle of a run ====
        $display("TEST 8: reset in the middle of green");
        wait_for_green_start;
        repeat (3) @(negedge clk);
        rst_n = 1'b0;                  // reset arrives partway through green
        repeat (2) @(negedge clk);
        rst_n = 1'b1;
        @(posedge clk); #1;
        check(car_red === 1'b1, "a reset in the middle of a run goes straight to RED");
        wait_for_green_start;          // the red after the reset has now finished
        $display("     measured: red after the reset lasted %0d ticks (should be 10)", last_red);
        check(last_red == RED_TIME, "after a reset, red lasts the full 10 ticks");
        $display("");

        // ==== the whole-run sanity rules ====
        $display("TEST 9: sanity checks across the whole run");
        check(onehot_errors == 0, "exactly one of red/yellow/green on at all times");
        check(walk_errors == 0, "walk is on during all of red, and off during green and yellow");
        $display("");

        // ==== summary ====
        $display("=====================================================");
        if (failed == 0) begin
            $display("  ALL %0d CHECKS PASSED", passed);
            $display("");
            $display("  Now open the waveform (make wave) and take your");
            $display("  screenshot. You still need that to turn in.");
        end else begin
            $display("  %0d passed, %0d FAILED", passed, failed);
            $display("");
            $display("  Open the waveform (make wave) and find where it");
            $display("  goes wrong. Check TROUBLESHOOTING.md.");
        end
        $display("=====================================================");
        $display("");
        $finish;
    end

endmodule
